### ISSUE TITLE
make swipe exceptions user-configurable

### ISSUE THREAD

**Issue by zanna-37** [zanna-37/hass-swipe-navigation#2]
# Enhancements
## Provide a way to bypass the default hard-coded exceptions
This could be easily done with a flag `use_default_exceptions` which defaults to `true`.

```yaml
swipe_nav:
  use_default_exceptions: false
```

This flag would be quite useless alone, therefore the user should be able to add custom exceptions.

## Provide a way for the user to add exceptions

```yaml
swipe_nav:
  custom_exceptions:
    - tagname: div
      css_class_list:
        - class1
        - class2
    - tagname: special-tag
    - tagname: g
      css_class_list:
        - my-special-class
```

# Drawbacks
In this implementation, when setting `use_default_exceptions` to `false` the user needs to manually copy the hard-coded exception list and put them as custom_exceptions. And although it is suboptimal, it is not that uncommon. Home Assistant default configuration [works in the same way](https://www.home-assistant.io/integrations/default_config/).
I think that creating a system of inclusions/exclusions would only complicate things with little gain since I suspect that `use_default_exceptions` would only be used in rare circumstances.

-----
See also:
- [mayker comment](https://community.home-assistant.io/t/lovelace-swipe-navigation/113806/187) on the home assistant community.
