### ISSUE TITLE
Increment helper value on swipe

### ISSUE THREAD

**Issue by Timmwardion** [zanna-37/hass-swipe-navigation#22]
Hi all. I'd like to increment (or decrement) a helper value as I swipe through the cards in the swipe nav. Is there a way I can do this?

I'm creating a day-view calendar carousel. So I'm hoping that I can swipe right to go up a day, and left to go down a day.

I can do this via a button as below but a swipe would be much more preferable.
```
              tap_action:
                  action: call-service
                  service: input_number.decrement
                  data: {}
                  target:
                    entity_id: input_number.calendarpage
```
