### ISSUE TITLE
Can't swipe over an iframe

### ISSUE THREAD

**Issue by fjeddy** [zanna-37/hass-swipe-navigation#23]
I am using a panel with an iframe that is purely for the purpose of providing read-only information. It could just as well be a picture, but as it happens, it's a website, regardless I'm assuming it's the iframe that's the problem.

Sliding doesn't work on the iframe. Being a panel isn't relevant, but in this case, panel makes it a full-screen one-card only, so getting out of the screen using slide gestures is literally impossible.

```yaml
title: "MyTestSubviewUsingAPanel"
path: someKindOfPath
icon: "mdi:icon"
type: panel
subview: true
cards:
  - type: "iframe"
    url: https://google.com
    aspect_ratio: 16:10
```
