### ISSUE TITLE
Swiping on apexcharts-card graph causes view to change

### ISSUE THREAD

**Issue by alexruffell** [zanna-37/hass-swipe-navigation#30]
When dragging a `custom:apexcharts-card` graph to see more data, the view is changed. Can you kindly add an exception for Apex Charts?

My Apex Chart is inside another card so just in case I am providing the YAML of the whole thing:

```
type: custom:tabbed-card
tabs:
  - card:
      type: custom:apexcharts-card
      header:
        show: true
        title: Fridge
        show_states: true
        colorize_states: true
      yaxis:
        - id: temperature
          decimals: 1
          max: 10
          min: 0
        - id: humidity
          decimals: 0
          max: 100
          min: 0
          opposite: true
      apex_config:
        legend:
          show: false
      all_series_config:
        stroke_width: 2
        curve: smooth
      series:
        - entity: sensor.fridge_sensor_temperature
          yaxis_id: temperature
          name: Temperature
        - entity: sensor.fridge_sensor_humidity
          yaxis_id: humidity
          name: Humidity
          unit: '%Rh'
    attributes:
      label: Fridge
  - card:
      type: statistics-graph
      chart_type: line
      period: hour
      days_to_show: 2
      entities:
        - sensor.fridge_sensor_temperature
      stat_types:
        - mean
        - min
        - max
      card_mod:
        style:
          .: |
            h1 {
              font-size: 18px;
              padding: 2px 15px 2px 15px
            }
          statistics-chart$ha-chart-base$: |
            .chartLegend { 
              display: none;
            }
    attributes:
      label: Temperature
  - card:
      type: statistics-graph
      chart_type: line
      period: hour
      days_to_show: 2
      entities:
        - sensor.fridge_sensor_humidity
      stat_types:
        - mean
        - min
        - max
      card_mod:
        style:
          .: |
            h1 {
              font-size: 18px;
              padding: 2px 15px 2px 15px
            }
          statistics-chart$ha-chart-base$: |
            .chartLegend { 
              display: none;
            }
    attributes:
      label: Humidity

```
