### ISSUE TITLE
Swipe on UI Minimalst cards

### ISSUE THREAD

**Issue by albinmedoc** [zanna-37/hass-swipe-navigation#38]
Swiping doesn´t work on UI Minimalist cards. 
I'm **not** getting any of the below messages in the console:
`↔️ Swipe navigation: [D] Ignoring touch on "app-header".`
`↔️ Swipe navigation: [D] Swipe ignored, too short.`
`↔️ Swipe navigation: [D] Swipe ignored, vertical movement.`
`↔️ Swipe navigation: [D] Ignoring touch: multiple touchpoints detected.`

Is there anything we can do in the repository to enable swipe?

**Comment by zanna-37** [comment]
Swipe navigation should work by default, are you sure you included everything?
I don't use UI Lovelace Minimalist, does it use the standard dashboard view?

**Comment by albinmedoc** [comment]
What do you mean by the standard dashboard view. How do I now?

This is my panels:
<img width="808" alt="Skärmavbild 2023-02-16 kl  07 06 54" src="https://user-images.githubusercontent.com/7331299/219282558-25550f5e-cc68-45f5-90e8-0fb4007b50c1.png">

The swiping is working if I'm not swiping over a card (a empty space).

**Comment by albinmedoc** [comment]
I have tested a bit and it seems like only the #handleTouchMove function is getting called. 


#handleTouchStart, #handleTouchEnd is not called.

**Comment by zanna-37** [comment]
I have no idea why this is. They are attached to the same element, so that's really strange.

Can you send me a minimal configuration that I can try? I need to reproduce the bug.

**Comment by albinmedoc** [comment]
You need to [install UI Lovelace Minimalst through HACS](https://ui-lovelace-minimalist.github.io/UI/setup/download/#hacs-download). 

Here is a minimal configuration (ui-lovelace.yaml)
```
---
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "Minimalist"
background: "var(--background-image)"
swipe_nav:
  animate: swipe
  prevent_default: true
  swipe_amount: 30
  logger_level: verbose
views:
  title: "Vardagsrum"
  path: "living-room"
  cards:
    - type: "horizontal-stack"
      cards:
        - type: "custom:button-card"
          template: chip_back
          variables:
            ulm_chip_back_path: /ui-lovelace-minimalist/home
        - type: "custom:button-card"
          template: card_title
          name: "Living room"

    - type: "custom:button-card"
      template: card_media_player
      entity: media_player.tv_living_room

    - type: "custom:button-card"
      template: card_light
      entity: light.dining_table_living_room
```
