### ISSUE TITLE
Bug: Swipe navigation is not working with sub_view

### ISSUE THREAD

**Issue by martindybal** [zanna-37/hass-swipe-navigation#68]
Swipe navigation is not working from subview to main view. There is a repro dashboard. Name your dashboard `dashboard-test2` or change navigation path to work for you. 

```
title: Not working swipe

swipe_nav:
  animate: swipe
  animate_duration: 150
  
views:
  - title: Not working swipe
    subview: false
    icon: mdi:home-outline
    path: overview
    badges: []
    cards:
      - type: button
        name: Go to Subview
        icon: mdi:arrow-collapse-right
        tap_action:
          action: navigate
          navigation_path: /dashboard-test2/Subview 
  - title: Subview
    subview: true
    path: Subview
    cards:
      - type: custom:mushroom-title-card
        title: 'This is subview. '
        subtitle: Swipe navigation to main view is not working
```
