### ISSUE TITLE
URL arguments not being passed to new view

### ISSUE THREAD

**Issue by wambs** [zanna-37/hass-swipe-navigation#85]
Hi,
Since a recent update to both wallpanel and swipe_nav, I have a problem passing the URL arguments to the new view.

For example:
When I access my HA web site, using the following:
https://mywebsite.com/lovelace-mainfloorplan/livingfloor?wp_enabled=false

This comes up OK. But, when I swipe to another view, the argument "wp_enabled=false", is no longer in the URL. 
So my view goes Fullscreen since that is the default.

Is anyone else having this issue?

```
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true

swipe_nav:
  wrap: true
  enable_mouse_swipe: true
  animate: flip
  prevent_default: true
  swipe_amount: 20
views:
```
